### ISSUE TITLE
部分证书没有编入 p7b 文件 Some certificates are not compiled into the p7b file

### ISSUE THREAD

**Issue by yihanwu1024** [yihanwu1024/badcert#4]
Ex:
![image](https://user-images.githubusercontent.com/48046869/85350725-78553b80-b534-11ea-9f61-5334ff32d3e1.png)
但是发布的证书中少了两个。
是不是 openssl 的问题？

**Comment by Liu233w** [comment]
emmmm确实

那4个文件的文件名是啥？我排查一下。

**Comment by yihanwu1024** [comment]
> emmmm确实
> 
> 那4个文件的文件名是啥？我排查一下。

看 CN，另外还发现四川悠闲的熊猫也没了

**Comment by Liu233w** [comment]
我知道为啥了。这个得保存成base64格式的文件才行，你保存成二进制格式了。

**Comment by yihanwu1024** [comment]
> 我知道为啥了。这个得保存成base64格式的文件才行，你保存成二进制格式了。

好，看来 Windows 导出之后要转换一下

**Comment by Liu233w** [comment]
> 
> 
> > 我知道为啥了。这个得保存成base64格式的文件才行，你保存成二进制格式了。
> 
> 好，看来 Windows 导出之后要转换一下

windows导出的时候可以选base64格式的。
![image](https://user-images.githubusercontent.com/16333687/85487340-ba9f7b00-b60f-11ea-8945-2134c3ab81ef.png)
